sudo: false
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
before_install:
- pip install --upgrade pip wheel
- pip install poetry
install:
- poetry install
- make install
script:
- make test
